(function(b){b.cluetip={version:"1.1.3",setup:{insertionType:"appendTo",insertionElement:"body"},defaults:{width:275,height:"auto",cluezIndex:97,positionBy:"auto",topOffset:15,leftOffset:15,local:false,localPrefix:null,localIdSuffix:null,hideLocal:true,attribute:"rel",titleAttribute:"title",splitTitle:"",escapeTitle:false,showTitle:true,cluetipClass:"default",hoverClass:"",waitImage:true,cursor:"help",arrows:false,dropShadow:true,dropShadowSteps:6,sticky:false,mouseOutClose:false,activation:"hover",
clickThrough:true,tracking:false,delayedClose:0,closePosition:"top",closeText:"Close",truncate:0,fx:{open:"show",openSpeed:""},hoverIntent:{sensitivity:3,interval:50,timeout:0},onActivate:function(){return true},onShow:function(){},onHide:function(){},ajaxCache:true,ajaxProcess:function(i){return i=i.replace(/<(script|style|title)[^<]+<\/(script|style|title)>/gm,"").replace(/<(link|meta)[^>]+>/g,"")},ajaxSettings:{dataType:"html"},debug:false}};var e,g,Q,E,F,G,X,H;b.fn.cluetip=function(i,p){function I(j,
k){j=j.dropShadow&&j.dropShadowSteps?+j.dropShadowSteps:0;if(b.support.boxShadow){k=j===0?"0 0 ":"1px 1px ";b("#cluetip").css(b.support.boxShadow,k+j+"px rgba(0,0,0,0.5)");return false}k=b("#cluetip .cluetip-drop-shadow");if(j==k.length)return k;k.remove();k=[];for(var h=0;h<j;)k[h++]='<div style="top:'+h+"px;left:"+h+'px;"></div>';return k=b(k.join("")).css({position:"absolute",backgroundColor:"#000",zIndex:q-1,opacity:0.1}).addClass("cluetip-drop-shadow").prependTo("#cluetip")}if(typeof i=="object"){p=
i;i=null}if(i=="destroy"){b(document).unbind(".cluetip");b("#cluetip").remove();b.removeData(this,"title");b.removeData(this,"cluetip");return this.unbind(".cluetip")}p=b.extend(true,{},b.cluetip.defaults,p||{});var J=/appendTo|prependTo|insertBefore|insertAfter/.test(p.insertionType)?p.insertionType:"appendTo",Y=p.insertionElement||"body";if(!b("#cluetip").length){b('<div id="cluetip"><div id="cluetip-outer" class="ui-cluetip-outer"><h3 id="cluetip-title" class="ui-widget-header ui-cluetip-header"></h3><div id="cluetip-inner" class="ui-widget-content ui-cluetip-content"></div></div><div id="cluetip-extra"></div><div id="cluetip-arrows" class="cluetip-arrows"></div></div>')[J](Y).hide();
var q=+p.cluezIndex;e=b("#cluetip").css({position:"absolute"});Q=b("#cluetip-outer").css({position:"relative",zIndex:q});g=b("#cluetip-inner");E=b("#cluetip-title");F=b("#cluetip-arrows");G=b('<div id="cluetip-waitimage"></div>').css({position:"absolute"}).insertBefore(e).hide()}var R=(parseInt(e.css("paddingLeft"),10)||0)+(parseInt(e.css("paddingRight"),10)||0);this.each(function(j){function k(){return false}var h=this,d=b(this),a=b.extend(true,{},p,b.metadata?d.metadata():b.meta?d.data():{}),aa=
false,A=false,ba=0,n=d.attr(a.attribute),K=a.cluetipClass;q=+a.cluezIndex;d.data("cluetip",{title:h.title,zIndex:q});if(!n&&!a.splitTitle&&!i)return true;if(a.local&&a.localPrefix)n=a.localPrefix+n;a.local&&a.hideLocal&&n&&b(n+":first").hide();var t=parseInt(a.topOffset,10),z=parseInt(a.leftOffset,10),w,Z,S=isNaN(parseInt(a.height,10))?"auto":/\D/g.test(a.height)?a.height:a.height+"px",T,x,u,L,U,$=parseInt(a.width,10)||275,o=$+R+a.dropShadowSteps,M=this.offsetWidth,y,l,r,B,C,s=a.attribute!="title"?
d.attr(a.titleAttribute):"";if(a.splitTitle){if(s==undefined)s="";C=s.split(a.splitTitle);s=C.shift()}if(a.escapeTitle)s=s.replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;");var V=function(c){if(a.onActivate(d)===false)return false;A=true;e.removeClass().css({width:$});n==d.attr("href")&&d.css("cursor",a.cursor);a.hoverClass&&d.addClass(a.hoverClass);x=d.offset().top;y=d.offset().left;r=c.pageX;L=c.pageY;if(h.tagName.toLowerCase()!="area"){T=b(document).scrollTop();B=b(window).width()}if(a.positionBy==
"fixed"){l=M+y+z;e.css({left:l})}else{l=M>y&&y>o||y+M+o+z>B?y-o-z:M+y+z;if(h.tagName.toLowerCase()=="area"||a.positionBy=="mouse"||M+o>B)if(r+20+o>B){e.addClass(" cluetip-"+K);l=r-o-z>=0?r-o-z-parseInt(e.css("marginLeft"),10)+parseInt(g.css("marginRight"),10):r-o/2}else l=r+z;var f=l<0?c.pageY+t:c.pageY;e.css({left:l>0&&a.positionBy!="bottomTop"?l:r+o/2>B?B/2-o/2:Math.max(r-o/2,0),zIndex:d.data("cluetip").zIndex});F.css({zIndex:d.data("cluetip").zIndex+1})}Z=b(window).height();if(i){if(typeof i==
"function")i=i.call(h);g.html(i);D(f)}else if(C){c=C.length;g.html(c?C[0]:"");if(c>1)for(var N=1;N<c;N++)g.append('<div class="split-body">'+C[N]+"</div>");D(f)}else if(!a.local&&n.indexOf("#")!==0)if(/\.(jpe?g|tiff?|gif|png)(?:\?.*)?$/i.test(n)){g.html('<img src="'+n+'" alt="'+s+'" />');D(f)}else{var O=a.ajaxSettings.beforeSend,ca=a.ajaxSettings.error,da=a.ajaxSettings.success,ea=a.ajaxSettings.complete;c=b.extend(true,{},a.ajaxSettings,{cache:a.ajaxCache,url:n,beforeSend:function(m){O&&O.call(h,
m,e,g);Q.children().empty();a.waitImage&&G.css({top:L+20,left:r+20,zIndex:d.data("cluetip").zIndex-1}).show()},error:function(m,v){if(A)ca?ca.call(h,m,v,e,g):g.html("<i>sorry, the contents could not be loaded</i>")},success:function(m,v){aa=a.ajaxProcess.call(h,m);if(A){da&&da.call(h,m,v,e,g);g.html(aa)}},complete:function(m,v){ea&&ea.call(h,m,v,e,g);m=g[0].getElementsByTagName("img");H=m.length;v=0;for(var ga=m.length;v<ga;v++)m[v].complete&&H--;if(H&&!b.browser.opera)b(m).bind("load error",function(){H--;
if(H<1){G.hide();A&&D(f)}});else{G.hide();A&&D(f)}}});b.ajax(c)}else if(a.local){c=b(n+(/#\S+$/.test(n)?"":":eq("+j+")")).clone(true).show();a.localIdSuffix&&c.attr("id",c[0].id+a.localIdSuffix);g.html(c);D(f)}},D=function(c){e.addClass("cluetip-"+K);if(a.truncate){var f=g.text().slice(0,a.truncate)+"...";g.html(f)}s?E.show().html(s):a.showTitle?E.show().html("&nbsp;"):E.hide();if(a.sticky){f=b('<div id="cluetip-close"><a href="#">'+a.closeText+"</a></div>");a.closePosition=="bottom"?f.appendTo(g):
a.closePosition=="title"?f.prependTo(E):f.prependTo(g);f.bind("click.cluetip",function(){P();return false});a.mouseOutClose?e.bind("mouseleave.cluetip",function(){P()}):e.unbind("mouseleave.cluetip")}f="";Q.css({zIndex:d.data("cluetip").zIndex,overflow:S=="auto"?"visible":"auto",height:S});w=S=="auto"?Math.max(e.outerHeight(),e.height()):parseInt(S,10);u=x;U=T+Z;if(a.positionBy=="fixed")u=x-a.dropShadowSteps+t;else if(l<r&&Math.max(l,0)+o>r||a.positionBy=="bottomTop")if(x+w+t>U&&L-T>w+t){u=L-w-t;
f="top"}else{u=L+t;f="bottom"}else u=x+w+t>U?w>=Z?T:U-w-t:d.css("display")=="block"||h.tagName.toLowerCase()=="area"||a.positionBy=="mouse"?c-t:x-a.dropShadowSteps;if(f=="")l<y?(f="left"):(f="right");c=" clue-"+f+"-"+K+" cluetip-"+K;if(K=="rounded")c+=" ui-corner-all";e.css({top:u+"px"}).attr({className:"ui-widget ui-widget-content ui-cluetip"+c});if(a.arrows){c=x-u-a.dropShadowSteps;F.css({top:/(left|right)/.test(f)&&l>=0&&c>0?c+"px":/(left|right)/.test(f)?0:""}).show()}else F.hide();(X=I(a))&&X.length&&
X.hide().css({height:w,width:$,zIndex:d.data("cluetip").zIndex-1}).show();e.hide()[a.fx.open](a.fx.openSpeed||0);b.fn.bgiframe&&e.bgiframe();if(a.delayedClose>0)ba=setTimeout(P,a.delayedClose);a.onShow.call(h,e,g)},W=function(){A=false;G.hide();if(!a.sticky||/click|toggle/.test(a.activation)){P();clearTimeout(ba)}a.hoverClass&&d.removeClass(a.hoverClass)},P=function(){Q.parent().hide().removeClass();a.onHide.call(h,e,g);d.removeClass("cluetip-clicked");s&&d.attr(a.titleAttribute,s);d.css("cursor",
"");a.arrows&&F.css({top:""})};b(document).bind("hideCluetip",function(){P()});if(/click|toggle/.test(a.activation))d.bind("click.cluetip",function(c){if(e.is(":hidden")||!d.is(".cluetip-clicked")){V(c);b(".cluetip-clicked").removeClass("cluetip-clicked");d.addClass("cluetip-clicked")}else W(c);return false});else if(a.activation=="focus"){d.bind("focus.cluetip",function(c){d.attr("title","");V(c)});d.bind("blur.cluetip",function(c){d.attr("title",d.data("thisInfo").title);W(c)})}else{d[a.clickThrough?
"unbind":"bind"]("click.cluetip",k);var fa=function(c){if(a.tracking==true){var f=l-c.pageX,N=u?u-c.pageY:x-c.pageY;d.bind("mousemove.cluetip",function(O){e.css({left:O.pageX+f,top:O.pageY+N})})}};b.fn.hoverIntent&&a.hoverIntent?d.hoverIntent({sensitivity:a.hoverIntent.sensitivity,interval:a.hoverIntent.interval,over:function(c){V(c);fa(c)},timeout:a.hoverIntent.timeout,out:function(c){W(c);d.unbind("mousemove.cluetip")}}):d.bind("mouseenter.cluetip",function(c){V(c);fa(c)}).bind("mouseleave.cluetip",
function(c){W(c);d.unbind("mousemove.cluetip")});d.bind("mouseover.cluetip",function(){d.attr("title","")}).bind("mouseleave.cluetip",function(){d.attr("title",d.data("cluetip").title)})}});return this};(function(){b.support=b.support||{};for(var i=document.createElement("div").style,p=["boxShadow"],I=["moz","Moz","webkit","o"],J=0,Y=p.length;J<Y;J++){var q=p[J],R=q.charAt(0).toUpperCase()+q.slice(1);if(typeof i[q]!=="undefined")b.support[q]=q;else for(var j=0,k=I.length;j<k;j++)if(typeof i[I[j]+
R]!=="undefined"){b.support[q]=I[j]+R;break}}})();b.fn.cluetip.defaults=b.cluetip.defaults})(jQuery);
