(function(c){c.fmatter={};c.extend(c.fmatter,{isBoolean:function(a){return typeof a==="boolean"},isObject:function(a){return a&&(typeof a==="object"||c.isFunction(a))||false},isString:function(a){return typeof a==="string"},isNumber:function(a){return typeof a==="number"&&isFinite(a)},isNull:function(a){return a===null},isUndefined:function(a){return typeof a==="undefined"},isValue:function(a){return this.isObject(a)||this.isString(a)||this.isNumber(a)||this.isBoolean(a)},isEmpty:function(a){if(!this.isString(a)&&
this.isValue(a))return false;else if(!this.isValue(a))return true;a=c.trim(a).replace(/\&nbsp\;/ig,"").replace(/\&#160\;/ig,"");return a===""}});c.fn.fmatter=function(a,b,d,e,f){var h=b;d=c.extend({},c.jgrid.formatter,d);if(c.fn.fmatter[a])h=c.fn.fmatter[a](b,d,e,f);return h};c.fmatter.util={NumberFormat:function(a,b){c.fmatter.isNumber(a)||(a*=1);if(c.fmatter.isNumber(a)){var d=a<0,e=a+"",f=b.decimalSeparator?b.decimalSeparator:".";if(c.fmatter.isNumber(b.decimalPlaces)){var h=b.decimalPlaces;e=
Math.pow(10,h);e=Math.round(a*e)/e+"";a=e.lastIndexOf(".");if(h>0){if(a<0){e+=f;a=e.length-1}else if(f!==".")e=e.replace(".",f);for(;e.length-1-a<h;)e+="0"}}if(b.thousandsSeparator){h=b.thousandsSeparator;a=e.lastIndexOf(f);a=a>-1?a:e.length;f=e.substring(a);for(var g=-1,i=a;i>0;i--){g++;if(g%3===0&&i!==a&&(!d||i>1))f=h+f;f=e.charAt(i-1)+f}e=f}e=b.prefix?b.prefix+e:e;return e=b.suffix?e+b.suffix:e}else return a},DateFormat:function(a,b,d,e){var f=/^\/Date\((([-+])?[0-9]+)(([-+])([0-9]{2})([0-9]{2}))?\)\/$/,
h=typeof b==="string"?b.match(f):null;f=function(m,r){m=String(m);for(r=parseInt(r,10)||2;m.length<r;)m="0"+m;return m};var g={m:1,d:1,y:1970,h:0,i:0,s:0,u:0},i=0,j,k=["i18n"];k.i18n={dayNames:e.dayNames,monthNames:e.monthNames};if(a in e.masks)a=e.masks[a];if(!isNaN(b-0)&&String(a).toLowerCase()=="u")i=new Date(parseFloat(b)*1E3);else if(b.constructor===Date)i=b;else if(h!==null){i=new Date(parseInt(h[1],10));if(h[3]){a=Number(h[5])*60+Number(h[6]);a*=h[4]=="-"?1:-1;a-=i.getTimezoneOffset();i.setTime(Number(Number(i)+
a*60*1E3))}}else{b=String(b).split(/[\\\/:_;.,\t\T\s-]/);a=a.split(/[\\\/:_;.,\t\T\s-]/);h=0;for(j=a.length;h<j;h++){if(a[h]=="M"){i=c.inArray(b[h],k.i18n.monthNames);if(i!==-1&&i<12)b[h]=i+1}if(a[h]=="F"){i=c.inArray(b[h],k.i18n.monthNames);if(i!==-1&&i>11)b[h]=i+1-12}if(b[h])g[a[h].toLowerCase()]=parseInt(b[h],10)}if(g.f)g.m=g.f;if(g.m===0&&g.y===0&&g.d===0)return"&#160;";g.m=parseInt(g.m,10)-1;i=g.y;if(i>=70&&i<=99)g.y=1900+g.y;else if(i>=0&&i<=69)g.y=2E3+g.y;i=new Date(g.y,g.m,g.d,g.h,g.i,g.s,
g.u)}if(d in e.masks)d=e.masks[d];else d||(d="Y-m-d");a=i.getHours();b=i.getMinutes();g=i.getDate();h=i.getMonth()+1;j=i.getTimezoneOffset();var l=i.getSeconds(),o=i.getMilliseconds(),n=i.getDay(),p=i.getFullYear(),q=(n+6)%7+1,s=(new Date(p,h-1,g)-new Date(p,0,1))/864E5,t={d:f(g),D:k.i18n.dayNames[n],j:g,l:k.i18n.dayNames[n+7],N:q,S:e.S(g),w:n,z:s,W:q<5?Math.floor((s+q-1)/7)+1:Math.floor((s+q-1)/7)||(((new Date(p-1,0,1)).getDay()+6)%7<4?53:52),F:k.i18n.monthNames[h-1+12],m:f(h),M:k.i18n.monthNames[h-
1],n:h,t:"?",L:"?",o:"?",Y:p,y:String(p).substring(2),a:a<12?e.AmPm[0]:e.AmPm[1],A:a<12?e.AmPm[2]:e.AmPm[3],B:"?",g:a%12||12,G:a,h:f(a%12||12),H:f(a),i:f(b),s:f(l),u:o,e:"?",I:"?",O:(j>0?"-":"+")+f(Math.floor(Math.abs(j)/60)*100+Math.abs(j)%60,4),P:"?",T:(String(i).match(/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g)||[""]).pop().replace(/[^-+\dA-Z]/g,""),Z:"?",c:"?",r:"?",U:Math.floor(i/1E3)};return d.replace(/\\.|[dDjlNSwzWFmMntLoYyaABgGhHisueIOPTZcrU]/g,
function(m){return m in t?t[m]:m.substring(1)})}};c.fn.fmatter.defaultFormat=function(a,b){return c.fmatter.isValue(a)&&a!==""?a:b.defaultValue?b.defaultValue:"&#160;"};c.fn.fmatter.email=function(a,b){return c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):'<a href="mailto:'+a+'">'+a+"</a>"};c.fn.fmatter.checkbox=function(a,b){var d=c.extend({},b.checkbox);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));b=d.disabled===true?'disabled="disabled"':"";
if(c.fmatter.isEmpty(a)||c.fmatter.isUndefined(a))a=c.fn.fmatter.defaultFormat(a,d);a+="";a=a.toLowerCase();return'<input type="checkbox" '+(a.search(/(false|0|no|off)/i)<0?" checked='checked' ":"")+' value="'+a+'" offval="no" '+b+"/>"};c.fn.fmatter.link=function(a,b){var d={target:b.target},e="";c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(d.target)e="target="+d.target;return c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):"<a "+e+' href="'+
a+'">'+a+"</a>"};c.fn.fmatter.showlink=function(a,b){var d={baseLinkUrl:b.baseLinkUrl,showAction:b.showAction,addParam:b.addParam||"",target:b.target,idName:b.idName},e="";c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(d.target)e="target="+d.target;d=d.baseLinkUrl+d.showAction+"?"+d.idName+"="+b.rowId+d.addParam;return c.fmatter.isString(a)||c.fmatter.isNumber(a)?"<a "+e+' href="'+d+'">'+a+"</a>":c.fn.fmatter.defaultFormat(a,b)};c.fn.fmatter.integer=
function(a,b){var d=c.extend({},b.integer);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(c.fmatter.isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.number=function(a,b){var d=c.extend({},b.number);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(c.fmatter.isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.currency=function(a,b){var d=
c.extend({},b.currency);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));if(c.fmatter.isEmpty(a))return d.defaultValue;return c.fmatter.util.NumberFormat(a,d)};c.fn.fmatter.date=function(a,b,d,e){d=c.extend({},b.date);c.fmatter.isUndefined(b.colModel.formatoptions)||(d=c.extend({},d,b.colModel.formatoptions));return!d.reformatAfterEdit&&e=="edit"?c.fn.fmatter.defaultFormat(a,b):c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):c.fmatter.util.DateFormat(d.srcformat,
a,d.newformat,d)};c.fn.fmatter.select=function(a,b){a+="";var d=false,e=[];if(c.fmatter.isUndefined(b.colModel.formatoptions)){if(!c.fmatter.isUndefined(b.colModel.editoptions))d=b.colModel.editoptions.value}else d=b.colModel.formatoptions.value;if(d){var f=b.colModel.editoptions.multiple===true?true:false,h=[],g;if(f){h=a.split(",");h=c.map(h,function(l){return c.trim(l)})}if(c.fmatter.isString(d))for(var i=d.split(";"),j=0,k=0;k<i.length;k++){g=i[k].split(":");if(g.length>2)g[1]=jQuery.map(g,function(l,
o){if(o>0)return l}).join(":");if(f){if(jQuery.inArray(g[0],h)>-1){e[j]=g[1];j++}}else if(c.trim(g[0])==c.trim(a)){e[0]=g[1];break}}else if(c.fmatter.isObject(d))if(f)e=jQuery.map(h,function(l){return d[l]});else e[0]=d[a]||""}a=e.join(", ");return a===""?c.fn.fmatter.defaultFormat(a,b):a};c.fn.fmatter.rowactions=function(a,b,d,e){var f={keys:false,onEdit:null,onSuccess:null,afterSave:null,onError:null,afterRestore:null,extraparam:{oper:"edit"},url:null,delOptions:{},editOptions:{}};a=c.jgrid.jqID(a);
b=c.jgrid.jqID(b);e=c("#"+b)[0].p.colModel[e];c.fmatter.isUndefined(e.formatoptions)||(f=c.extend(f,e.formatoptions));if(!c.fmatter.isUndefined(c("#"+b)[0].p.editOptions))f.editOptions=c("#"+b)[0].p.editOptions;if(!c.fmatter.isUndefined(c("#"+b)[0].p.delOptions))f.delOptions=c("#"+b)[0].p.delOptions;e=function(g){f.afterSave&&f.afterSave(g);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b+".ui-jqgrid-btable:first").show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel",
"#"+b+".ui-jqgrid-btable:first").hide()};var h=function(g){f.afterRestore&&f.afterRestore(g);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b+".ui-jqgrid-btable:first").show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b+".ui-jqgrid-btable:first").hide()};switch(d){case "edit":c("#"+b).jqGrid("editRow",a,f.keys,f.onEdit,f.onSuccess,f.url,f.extraparam,e,f.onError,h);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b+".ui-jqgrid-btable:first").hide();
c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b+".ui-jqgrid-btable:first").show();break;case "save":if(c("#"+b).jqGrid("saveRow",a,f.onSuccess,f.url,f.extraparam,e,f.onError,h)){c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del","#"+b+".ui-jqgrid-btable:first").show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b+".ui-jqgrid-btable:first").hide()}break;case "cancel":c("#"+b).jqGrid("restoreRow",a,h);c("tr#"+a+" div.ui-inline-edit, tr#"+a+" div.ui-inline-del",
"#"+b+".ui-jqgrid-btable:first").show();c("tr#"+a+" div.ui-inline-save, tr#"+a+" div.ui-inline-cancel","#"+b+".ui-jqgrid-btable:first").hide();break;case "del":c("#"+b).jqGrid("delGridRow",a,f.delOptions);break;case "formedit":c("#"+b).jqGrid("setSelection",a);c("#"+b).jqGrid("editGridRow",a,f.editOptions);break}};c.fn.fmatter.actions=function(a,b){a={keys:false,editbutton:true,delbutton:true,editformbutton:false};c.fmatter.isUndefined(b.colModel.formatoptions)||(a=c.extend(a,b.colModel.formatoptions));
var d=b.rowId,e="",f;if(typeof d=="undefined"||c.fmatter.isEmpty(d))return"";if(a.editformbutton){f="onclick=jQuery.fn.fmatter.rowactions('"+d+"','"+b.gid+"','formedit',"+b.pos+"); onmouseover=jQuery(this).addClass('ui-state-hover'); onmouseout=jQuery(this).removeClass('ui-state-hover'); ";e=e+"<div title='"+c.jgrid.nav.edittitle+"' style='float:left;cursor:pointer;' class='ui-pg-div ui-inline-edit' "+f+"><span class='ui-icon ui-icon-pencil'></span></div>"}else if(a.editbutton){f="onclick=jQuery.fn.fmatter.rowactions('"+
d+"','"+b.gid+"','edit',"+b.pos+"); onmouseover=jQuery(this).addClass('ui-state-hover'); onmouseout=jQuery(this).removeClass('ui-state-hover') ";e=e+"<div title='"+c.jgrid.nav.edittitle+"' style='float:left;cursor:pointer;' class='ui-pg-div ui-inline-edit' "+f+"><span class='ui-icon ui-icon-pencil'></span></div>"}if(a.delbutton){f="onclick=jQuery.fn.fmatter.rowactions('"+d+"','"+b.gid+"','del',"+b.pos+"); onmouseover=jQuery(this).addClass('ui-state-hover'); onmouseout=jQuery(this).removeClass('ui-state-hover'); ";
e=e+"<div title='"+c.jgrid.nav.deltitle+"' style='float:left;margin-left:5px;' class='ui-pg-div ui-inline-del' "+f+"><span class='ui-icon ui-icon-trash'></span></div>"}f="onclick=jQuery.fn.fmatter.rowactions('"+d+"','"+b.gid+"','save',"+b.pos+"); onmouseover=jQuery(this).addClass('ui-state-hover'); onmouseout=jQuery(this).removeClass('ui-state-hover'); ";e=e+"<div title='"+c.jgrid.edit.bSubmit+"' style='float:left;display:none' class='ui-pg-div ui-inline-save' "+f+"><span class='ui-icon ui-icon-disk'></span></div>";
f="onclick=jQuery.fn.fmatter.rowactions('"+d+"','"+b.gid+"','cancel',"+b.pos+"); onmouseover=jQuery(this).addClass('ui-state-hover'); onmouseout=jQuery(this).removeClass('ui-state-hover'); ";e=e+"<div title='"+c.jgrid.edit.bCancel+"' style='float:left;display:none;margin-left:5px;' class='ui-pg-div ui-inline-cancel' "+f+"><span class='ui-icon ui-icon-cancel'></span></div>";return"<div style='margin-left:8px;'>"+e+"</div>"};c.unformat=function(a,b,d,e){var f,h=b.colModel.formatter,g=b.colModel.formatoptions||
{},i=/([\.\*\_\'\(\)\{\}\+\?\\])/g,j=b.colModel.unformat||c.fn.fmatter[h]&&c.fn.fmatter[h].unformat;if(typeof j!=="undefined"&&c.isFunction(j))f=j(c(a).text(),b,a);else if(!c.fmatter.isUndefined(h)&&c.fmatter.isString(h)){f=c.jgrid.formatter||{};switch(h){case "integer":g=c.extend({},f.integer,g);b=g.thousandsSeparator.replace(i,"\\$1");b=new RegExp(b,"g");f=c(a).text().replace(b,"");break;case "number":g=c.extend({},f.number,g);b=g.thousandsSeparator.replace(i,"\\$1");b=new RegExp(b,"g");f=c(a).text().replace(b,
"").replace(g.decimalSeparator,".");break;case "currency":g=c.extend({},f.currency,g);b=g.thousandsSeparator.replace(i,"\\$1");b=new RegExp(b,"g");f=c(a).text().replace(b,"").replace(g.decimalSeparator,".").replace(g.prefix,"").replace(g.suffix,"");break;case "checkbox":g=b.colModel.editoptions?b.colModel.editoptions.value.split(":"):["Yes","No"];f=c("input",a).is(":checked")?g[0]:g[1];break;case "select":f=c.unformat.select(a,b,d,e);break;case "actions":return"";default:f=c(a).text()}}return f!==
undefined?f:e===true?c(a).text():c.jgrid.htmlDecode(c(a).html())};c.unformat.select=function(a,b,d,e){d=[];a=c(a).text();if(e===true)return a;b=c.extend({},b.colModel.editoptions);if(b.value){var f=b.value;b=b.multiple===true?true:false;e=[];var h;if(b){e=a.split(",");e=c.map(e,function(k){return c.trim(k)})}if(c.fmatter.isString(f))for(var g=f.split(";"),i=0,j=0;j<g.length;j++){h=g[j].split(":");if(h.length>2)h[1]=jQuery.map(h,function(k,l){if(l>0)return k}).join(":");if(b){if(jQuery.inArray(h[1],
e)>-1){d[i]=h[0];i++}}else if(c.trim(h[1])==c.trim(a)){d[0]=h[0];break}}else if(c.fmatter.isObject(f)||c.isArray(f)){b||(e[0]=a);d=jQuery.map(e,function(k){var l;c.each(f,function(o,n){if(n==k){l=o;return false}});if(typeof l!="undefined")return l})}return d.join(", ")}else return a||""};c.unformat.date=function(a,b){var d=c.jgrid.formatter.date||{};c.fmatter.isUndefined(b.formatoptions)||(d=c.extend({},d,b.formatoptions));return c.fmatter.isEmpty(a)?c.fn.fmatter.defaultFormat(a,b):c.fmatter.util.DateFormat(d.newformat,
a,d.srcformat,d)}})(jQuery);
