(function(){function E(q,l,s,t,w){var a=this;q=q;l=l;w=w;var z={cookie_service:{enabled:true},column_search:{enabled:true,regexp:true},columns_show_hide:{enabled:true},search_dialog:{enabled:true},csv_export:{enabled:true},global_search:{enabled:false},global_sort:{enabled:false}};this.configuration=s;this.operations=t.operations!==undefined?t.operations:{};this.templates=t.templates!==undefined?t.templates:{};this.features=t.features!==undefined?jQuery.extend(z,t.features):z;var F={datatype:function(b){r.list.process_data.retrieveData(b,
p.get(b.my_index))},viewrecords:true},A={edit:false,add:false,del:false,refreshtext:"Refresh",searchtext:"Filter",afterRefresh:function(){a.refreshData();a.jqgrid.object.trigger("reloadGrid")}};if(!a.features.search_dialog.enabled)A.search=false;this.jqgrid={id:null,object:null,options:null,last_selected_row:null,editable_columns:[],dirty_fields:{},pager:{id:null,options:null}};this.data={data:[],all_data:[],filtered_data:null};var v={enableDisableButtons:function(b){return function(e){function m(g){g=
jQuery("#"+b.jqgrid.id).jqGrid("getRowData",g);var c=g.key.toString(),d=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(c);if(d!==null)c=d[2];var j=x.from(b.data.all_data).equals("columns.key",c).select()[0];if(b.jqgrid.dirty_fields[c]===undefined)b.jqgrid.dirty_fields[c]=[];var k=[],n=[];jQuery.each(g,function(i,o){o=o.toString();var u=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(o);if(u!==null)o=u[2];u=j.columns[i];if(typeof u=="boolean")u=""+u;o!=u?k.push(i):n.push(i)});jQuery.each(k,function(i,
o){jQuery.inArray(o,b.jqgrid.dirty_fields[c])===-1&&b.jqgrid.dirty_fields[c].push(o)});jQuery.each(n,function(i,o){i=jQuery.inArray(o,b.jqgrid.dirty_fields[c]);i!==-1&&b.jqgrid.dirty_fields[c].splice(i,1)});b.jqgrid.dirty_fields[c].length===0&&delete b.jqgrid.dirty_fields[c];jQuery.each(b.operations.buttons,function(i,o){if(o.type==="post_edit"){i=jQuery("#"+b.jqgrid.id+"_buttonOp_"+o.id);if(jQuery.isEmptyObject(b.jqgrid.dirty_fields))i.attr("disabled","disabled");else{i.click();i.removeAttr("disabled")}}});
B()}var h=b.jqgrid.object.jqGrid("getGridParam","multiselect")?"selarrrow":"selrow",f=b.jqgrid.object.jqGrid("getGridParam",h);f instanceof Array||(f=[f]);if(f.length===1)if(e&&e!==b.jqgrid.last_selected_row){jQuery("#"+b.jqgrid.id).restoreRow(b.jqgrid.last_selected_row);jQuery("#"+b.jqgrid.id).jqGrid("editRow",e,true,null,null,"clientArray",null,m);b.jqgrid.last_selected_row=e}jQuery.each(b.operations.buttons,function(g,c){g=jQuery("#"+b.jqgrid.id+"_buttonOp_"+c.id);if(c.type!=="post_edit")if(f.length>=
c.real_bounds[0]&&f.length<=c.real_bounds[1]){g.removeAttr("disabled");if(c.real_bounds[0]===1&&c.real_bounds[1]===1&&g.data("melange")!==undefined){var d=b.jqgrid.object.jqGrid("getRowData",f[0]);d=x.from(b.data.all_data).equals("columns.key",d.key).select()[0];var j=g.data("melange").click;g.click(j(d.operations.buttons[c.id].link));g.attr("value",d.operations.buttons[c.id].caption)}}else g.attr("disabled","disabled")})}}(a),global_button_functions:{redirect_simple:function(b){return b.new_window?
function(){window.open(b.link)}:function(){window.location.href=b.link}},redirect_custom:function(b){return function(e){return b.new_window?function(){window.open(e)}:function(){window.location.href=e}}},post:function(b){return function(){var e=p.get(b.idx).jqgrid.object.jqGrid("getGridParam","multiselect")?"selarrrow":"selrow";e=p.get(b.idx).jqgrid.object.jqGrid("getGridParam",e);e instanceof Array||(e=e===null?[]:[e]);var m=[];if(!(e.length<b.real_bounds[0]||e.length>b.real_bounds[1])){jQuery.each(e,
function(h,f){var g=jQuery("#"+p.get(b.idx).jqgrid.id).jqGrid("getRowData",f);x.from(p.get(b.idx).all_data).equals("columns.key",g.key).select();var c={};jQuery.each(b.keys,function(d,j){d=g[j];if(jQuery(d).hasClass("listsnoul"))d=/^<a\b[^>]*>(.*?)<\/a>$/.exec(d)[1];c[j]=d});m.push(c)});if(b.url==="")b.url=window.location.href;jQuery.post(b.url,{xsrf_token:window.xsrf_token,idx:b.idx,button_id:b.button_id,data:JSON.stringify(m)},function(h){if(b.redirect=="true")try{var f=JSON.parse(h);if(f.data.url!==
undefined)window.location.href=f.data.url}catch(g){}h=parseInt(b.refresh,10);if(!isNaN(h)){p.get(h).refreshData();jQuery("#"+p.get(h).jqgrid.id).trigger("reloadGrid")}if(b.refresh=="current"){p.get(b.idx).refreshData();jQuery("#"+p.get(b.idx).jqgrid.id).trigger("reloadGrid")}else if(b.refresh=="all"){h=p.getAll();jQuery.each(h,function(c,d){d.refreshData();jQuery("#"+p.get(c).jqgrid.id).trigger("reloadGrid")})}})}}},post_edit:function(b){return function(){var e=p.get(b.idx).jqgrid,m={};if(!(e.editable_columns.length===
0&&jQuery.isEmptyObject(e.dirty_fields))){e.object.jqGrid("getGridParam","records");for(var h=e.object.jqGrid("getGridParam","reccount"),f=1;f<=h;f++){var g=jQuery("#"+e.id).jqGrid("getRowData",f),c=g.key.toString(),d=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(c);if(d!==null)c=d[2];if(e.dirty_fields[c]!==undefined){m[c]={};jQuery.each(e.dirty_fields[c],function(j,k){j=g[k].toString();var n=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(j);if(n!==null)j=n[2];m[c][k]=j});b.keys!==undefined&&
jQuery.each(b.keys,function(j,k){if(m[c][k]===undefined){j=g[k].toString();var n=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(j);if(n!==null)j=n[2];m[c][k]=j}})}}if(b.url==="")b.url=window.location.href;jQuery.post(b.url,{xsrf_token:window.xsrf_token,idx:b.idx,button_id:b.button_id,data:JSON.stringify(m)},function(j){if(b.redirect=="true")try{var k=JSON.parse(j);if(k.data.url!==undefined)window.location.href=k.data.url}catch(n){}j=parseInt(b.refresh,10);if(!isNaN(j)){p.get(j).refreshData();jQuery("#"+
p.get(j).jqgrid.id).trigger("reloadGrid")}if(b.refresh=="current"){p.get(b.idx).refreshData();jQuery("#"+p.get(b.idx).jqgrid.id).trigger("reloadGrid")}else if(b.refresh=="all"){j=p.getAll();jQuery.each(j,function(i,o){o.refreshData();jQuery("#"+p.get(i).jqgrid.id).trigger("reloadGrid")})}})}}}},row_functions:{redirect_custom:function(b){return function(e,m){return b.new_window||m.which===2||m.which===1&&m.ctrlKey?function(){window.open(e)}:function(){window.location.href=e}}}}},G=function(){jQuery("#"+
q).replaceWith(['<p id="temporary_list_placeholder_',l,'"></p>','<table id="'+a.jqgrid.id+'"',' cellpadding="0" cellspacing="0"></table>','<div id="'+a.jqgrid.pager.id+'"',' style="text-align:center"></div>'].join(""))},J=function(b,e){e.columns=H(e.columns);I(b,e)},I=function(b,e){if(e.operations===undefined||e.operations.row_buttons===undefined)return e;jQuery.each(e.operations.row_buttons,function(m,h){var f={};jQuery.each(h.buttons_def,function(k,n){if(n.type==="redirect_simple"){var i="row_button_"+
a.getIdx()+"_"+b+"_"+k,o="";if(n.classes!==undefined&&n.classes.length!==0)o=' class = "'+n.classes.join(" ")+'"';n=['<input type="button" value="',n.caption,'" id="',i,'"',o,"></input>"].join("");f[k]=n}});var g="";if(h.template===undefined||jQuery.trim(h.template)==="")jQuery.each(f,function(k){g+="{{ "+k+"}}"});else g=h.template;for(var c=/\{\{([^\}]+)\}\}/g,d=g;h=c.exec(g);){var j=jQuery.trim(h[1]);if(f[j]!==undefined)d=d.replace(h[0],f[j])}e.columns[m]+=d});return e},H=function(b){if(a.templates===
undefined)return b;b=b;jQuery.each(a.templates,function(e,m){for(var h,f=/\{\{([^\}]+)\}\}/g,g=m;h=f.exec(m);){var c=jQuery.trim(h[1]);if(b[c]!==undefined&&b[e]!==undefined)g=g.replace(h[0],b[c])}b[e]=g});return b},D=function(){var b="",e=0;jQuery("#load_"+a.jqgrid.id).show();var m=function(){var h="?";if(window.location.href.indexOf("?")!==-1)h="&";jQuery.ajax({async:true,cache:false,url:[window.location.href.split("#")[0],h,"fmt=json&limit=100",b===""?"":"&start="+b,"&idx=",l].join(""),timeout:6E4,
tryCount:1,retryLimit:5,error:function(f){if(f.status==500){this.tryCount++;if(this.tryCount<=this.retryLimit)jQuery.ajax(this);else{jQuery("#temporary_list_placeholder_"+l).html('<span style="color:red">Error retrieving data: please refresh the list or the whole page to try again</span>');jQuery("#load_"+a.jqgrid.id).hide()}}else{jQuery("#temporary_list_placeholder_"+l).html('<span style="color:red">Error retrieving data: please refresh the list or the whole page to try again</span>');jQuery("#load_"+
a.jqgrid.id).hide()}},success:function(f){var g=f.next==="done";if(f.data[b]!==undefined){if(a.configuration===null)a.configuration=f.configuration;if(a.operations===null)a.operations=f.operations;jQuery.each(f.data[b],function(c,d){J(c,d);a.data.data.push(d.columns);a.data.all_data.push(d)});a.jqgrid.object===null?C():a.jqgrid.object.trigger("reloadGrid");jQuery.each(a.data.all_data,function(c,d){d.operations!==undefined&&d.operations.row_buttons!==undefined&&jQuery.each(d.operations.row_buttons,
function(j,k){jQuery.each(k.buttons_def,function(n,i){n="row_button_"+a.getIdx()+"_"+c+"_"+n;i.type==="redirect_simple"&&jQuery("#"+n).click(v.global_button_functions[i.type](i.parameters))})})});if(g){jQuery("#temporary_list_placeholder_"+l).remove();jQuery("#load_"+a.jqgrid.id).hide()}else{b=f.next;setTimeout(m,100);e++}}if(g){jQuery("#temporary_list_placeholder_"+l).remove();jQuery("#load_"+a.jqgrid.id).hide();a.jqgrid.object.triggerToolbar!==undefined&&a.jqgrid.object.triggerToolbar();jQuery.each(a.configuration.colModel,
function(c,d){d.editable!==undefined&&d.editable===true&&a.jqgrid.editable_columns.push(d.name)});jQuery("#t_"+a.jqgrid.id).children().remove();a.operations!==undefined&&a.operations.buttons!==undefined&&jQuery.each(a.operations.buttons,function(c,d){c=a.jqgrid.id+"_buttonOp_"+d.id;var j=jQuery("<input type='button' value='"+d.caption+"' style='float:left' id='"+c+"'/>").button();jQuery("#t_"+a.jqgrid.id).append(j);d.parameters.idx=l;if(d.type!=="post_edit"){d.real_bounds=d.bounds;j=d.real_bounds.indexOf("all");
if(j!==-1)d.real_bounds[j]=a.jqgrid.object.jqGrid("getGridParam","records");d.parameters.real_bounds=d.real_bounds}if(d.type==="post_edit"||d.real_bounds[0]>0)jQuery("#"+c).attr("disabled","disabled");d.parameters.button_id=d.id;jQuery("#"+c).click(v.global_button_functions[d.type](d.parameters));d.type=="redirect_custom"&&jQuery("#"+c).data("melange",{click:v.global_button_functions[d.type](d.parameters)})});jQuery("#t_"+a.jqgrid.id).css("padding-bottom","3px");if(a.features.csv_export.enabled){jQuery("#t_"+
a.jqgrid.id).append("<input type='button' value='CSV Export' style='float:right;' id='csvexport_"+a.jqgrid.id+"'/>");jQuery("#csvexport_"+a.jqgrid.id).button();jQuery("#csvexport_"+a.jqgrid.id).click(function(){var c=[];c[0]=[];if(a.data.data[0]!==undefined||a.data.filtered_data[0]!==undefined){var d=a.data.filtered_data||a.data.data;jQuery.each(a.configuration.colNames,function(k,n){k=n;k=k.replace(/\"|&quot;|&#34;/g,'""');if(k.indexOf(",")!==-1||k.indexOf('"')!==-1||k.indexOf("\r\n")!==-1)k='"'+
k+'"';c[0].push(k)});c[0]=c[0].join(",");var j=[];jQuery.each(a.configuration.colModel,function(k,n){j.push(n.name)});jQuery.each(d,function(k,n){c[c.length]=[];jQuery.each(j,function(i,o){i=n[o];if(i===null)i="";if(i===undefined)i="";i=i.toString();o=/^<a\b[^>]*href="(.*?)" \b[^>]*>(.*?)<\/a>$/.exec(i);if(o!==null)i=o[1];i=i.replace(/\"|&quot;|&#34;/g,'""');if(i.indexOf(",")!==-1||i.indexOf('"')!==-1||i.indexOf("\r\n")!==-1)i='"'+i+'"';c[c.length-1].push(i)});c[c.length-1]=c[c.length-1].join(",")});
c=c.join("\r\n");jQuery("#csv_dialog").remove();jQuery("body").append(["<div id='csv_dialog' style='display:none'>  <h3>Now you can copy and paste CSV data from the text area to a new file:</h3>  <textarea style='width:450px;height:250px'>",c,"</textarea></div>"].join(""));jQuery("#csv_dialog").dialog({height:420,width:500,modal:true,buttons:{Close:function(){jQuery(this).dialog("close")}}})}})}if(a.features.column_search.enabled&&a.features.column_search.regexp){jQuery("#t_"+a.jqgrid.id).append("<div style='float:right;margin-right:4px;'><input type='checkbox' id='regexp_"+
a.jqgrid.id+"'/>RegExp Search</div>");jQuery("#regexp_"+a.jqgrid.id).click(function(){jQuery("#"+a.jqgrid.id).jqGrid().trigger("reloadGrid")})}f=jQuery.Event("melange_list_loaded");f.list_object=a;a.jqgrid.object.trigger(f);f=jQuery("#gview_"+a.jqgrid.id+" .ui-jqgrid-bdiv");f.width(f.width()+1)}}})};setTimeout(m,100)};this.refreshData=function(){a.data={data:[],all_data:[],filtered_data:null};D()};var B=function(){if(a.configuration.footerrow){var b={},e=a.jqgrid.object;jQuery.each(a.configuration.colModel,
function(m,h){if(h.summaryType!==undefined){m=e.jqGrid("getCol",h.name,false,h.summaryType);b[h.name]=h.summaryTpl.replace(/\{0\}/ig,m)}});e.jqGrid("footerData","set",b)}},K=function(){if(a.jqgrid.object){B();a.features.cookie_service.enabled&&r.list.cookie_service.saveCurrentTableConfiguration(l,a.jqgrid.object)}},C=function(){if(a.features.cookie_service.enabled)a.configuration=r.list.cookie_service.getPreviousTableConfiguration(l,a.configuration);var b=jQuery.extend(a.configuration,{postData:{my_index:l},
onSelectAll:v.enableDisableButtons,onSelectRow:v.enableDisableButtons,gridComplete:K,altRows:true,altclass:"alternate_row"}),e={caption:"Columns",buttonicon:"ui-icon-calculator",onClickButton:function(){var f=jQuery("#"+a.jqgrid.id).jqGrid("getGridParam","width");jQuery("#"+a.jqgrid.id).jqGrid("columnChooser",{done:function(g){if(g){this.jqGrid("remapColumns",g,true);this.jqGrid("setGridWidth",f);r.list.cookie_service.saveCurrentTableConfiguration(l,a.jqgrid.object)}}})},position:"last",title:"Show/Hide Columns",
cursor:"pointer"},m={};if(a.features.column_search.enabled)m={closeAfterSearch:true,multipleSearch:true};jQuery("#"+a.jqgrid.id).jqGrid(jQuery.extend(a.jqgrid.options,b)).jqGrid("navGrid","#"+a.jqgrid.pager.id,a.jqgrid.pager.options,{},{},{},m,{});a.features.columns_show_hide.enabled&&jQuery("#"+a.jqgrid.id).jqGrid("navButtonAdd","#"+a.jqgrid.pager.id,e);a.features.column_search.enabled&&jQuery("#"+a.jqgrid.id).jqGrid("filterToolbar",{beforeSearch:function(){r.list.cookie_service.saveCurrentTableConfiguration(l,
a.jqgrid.object)},searchOnEnter:false,autosearch:true});jQuery("#load_"+a.jqgrid.id).closest("div").css("line-height","100%");jQuery("#load_"+a.jqgrid.id).html("<img src='/soc/content/"+r.config.app_version+"/images/jqgrid_loading.gif'></img>");a.jqgrid.object=jQuery("#"+a.jqgrid.id);a.features.global_search.enabled&&jQuery(a.features.global_search.element_path).bind("keyup",function(){var f=jQuery(a.features.global_search.element_path).val(),g=a.jqgrid.object.jqGrid("getGridParam","postData");g._search=
true;g.filters={groupOp:"OR",rules:[]};jQuery.each(a.configuration.colModel,function(c,d){g.filters.rules.push({field:d.name,op:"cn",data:f})});g.filters=JSON.stringify(g.filters);a.jqgrid.object.jqGrid("setGridParam",{search:true,postData:g});a.jqgrid.object.trigger("reloadGrid")});b=a.features.global_sort;if(b.enabled){if(b.element_paths.column!==undefined){var h=jQuery(b.element_paths.column);jQuery(" option",h).remove();jQuery.each(a.configuration.colModel,function(f,g){h.append(jQuery("<option></option>").val(g.name).html(a.configuration.colNames[f]))});
e=a.jqgrid.object.jqGrid("getGridParam","postData").sidx;h.val(e);h.bind("change",function(){var f=jQuery(this).val();a.jqgrid.object.jqGrid("setGridParam",{sortname:f});a.jqgrid.object.trigger("reloadGrid")})}if(b.element_paths.asc_desc!==undefined){h=jQuery(b.element_paths.asc_desc);jQuery(" option",h).remove();h.append(jQuery("<option></option>").val("asc").html("Ascending"));h.append(jQuery("<option></option>").val("desc").html("Descending"));e=a.jqgrid.object.jqGrid("getGridParam","postData").sord;
h.val(e);h.bind("change",function(){var f=jQuery(this).val();a.jqgrid.object.jqGrid("setGridParam",{sortorder:f});a.jqgrid.object.trigger("reloadGrid")})}}};this.getDiv=function(){return q};this.getIdx=function(){return l};this.init=function(){jQuery(function(){if(jQuery("#"+q).length===0)throw new r.error.divNotExistent("Div "+q+" is not existent");a.jqgrid.id="jqgrid_"+q;a.jqgrid.pager.id="jqgrid_pager_"+q;a.jqgrid.options=jQuery.extend(F,{pager:"#"+a.jqgrid.pager.id});a.jqgrid.pager.options=A;
p.add(a);G();C();D()})};w!==undefined&&w===true?this.init():p.add(this)}if(window.melange===undefined)throw new Error("Melange not loaded");var r=window.melange;if(window.jLinq===undefined)throw new Error("jLinq not loaded");var x=window.jLinq;r.list=window.melange.list=function(){return new r.list};var y=r.logging.debugDecorator(r.list);r.error.createErrors(["listIndexNotValid","divNotExistent","indexAlreadyExistent"]);y.list_objects=function(){var q=[];return{add:function(l){q[l.getIdx()]=l},get:function(l){return q[l]!==
undefined?q[l]:null},getAll:function(){return jQuery.extend({},q)},isExistent:function(l){return q[l]!==undefined?true:false}}}();var p=y.list_objects;y.loadList=function(q,l,s,t){s=parseInt(s,10);l=JSON.parse(l);if(isNaN(s)||s<0)throw new r.error.listIndexNotValid("List index "+s+" is not valid");if(p.isExistent(s))throw new r.error.indexAlreadyExistent("Index "+s+" is already existent");new E(q,s,l.configuration,l,t)}})();
