(function(a){a(function(){function j(){d.find("td.twolineformfieldlabel > label").prepend(k).end();a("ol").find("li").each(function(){a(this).prepend(g.join(a(this).attr("id"))).end()});d.find(".short_answer").each(function(){a(this).attr("name",i+a(this).getPosition()+"short_answer__"+a(this).attr("name"))});d.find("[name=create-option-button]").each(function(){a("#index_for_"+a(this).attr("value")).val(a(this).getPosition())});d.find(".long_answer").each(function(){a(this).attr("name",i+a(this).getPosition()+
"long_answer__"+a(this).attr("name")).attr("overflow","auto")})}var d=a("div#survey_widget");d.parents("td.formfieldvalue:first").css({"float":"left",width:200});a("input#id_title").val()===""&&a(".formfielderror").length<1&&d.find("tr").remove();d.find("table:first").show();var i="survey__",k=["<a class='delete'><img ","src='/soc/content/"+melange.config.app_version+"/images/minus.gif'/></a>"].join(""),g=["<a class='delete_item' id='del_","' ><img src='/soc/content/"+melange.config.app_version+"/images/minus.gif'/></a> "],
f=a("form").find("#id_survey_html").attr("value");if(f&&f.length>1){d.html(f);d.find(".long_answer,input").each(function(){a(this).val(a(this).attr("val"))})}else j();var b=d.find("tbody:first"),l=d.find("#survey_options");a("form input, form button, form select").keypress(function(c){if(c.which&&c.which===13||c.keyCode&&c.keyCode===13){a(this).parents(".ui-dialog:first").find(":button:first").click();return false}});a("a.fetch_answers").click(function(){var c=this.id.replace("results_for_",""),e=
window.location.pathname;e=e.replace("/edit/","/show/").replace("/results/","/show/");var m="?read_only=true&user_results="+c;a('<div style="overflow-y: auto; margin-bottom: 100px;"></div>').load(e+m+" #survey_widget").dialog({title:c,height:500,width:700})});b.bind("init",function(){d.find("input").each(function(){if((a(this).val().length<1||a(this).val()==="Write a Custom Prompt...")&&a(this).attr("type")!=="hidden")a(this).preserveDefaultText("Write a Custom Prompt...")});d.find(".long_answer, .tooltip_entry").each(function(){if(a(this).val().length<
1||a(this).val()==="Write a Custom Prompt For This Question...")a(this).preserveDefaultText("Write a Custom Prompt For This Question...");a(this).TextAreaExpander(100,500)});d.find("a.delete img").click(function(){var c=a(this).parents("tr:first"),e=a(c).find("label").attr("for");if(confirm("Deleting this field will remove all answers submitted for this field. Continue?")){var m=a("#EditForm"),n=a("#__deleted__");if(n.val())n.val(n.val()+","+e.replace("id_","")).end();else{e=a("<input type='hidden' value='"+
e.replace("id_","")+"' />");e.attr({id:"__deleted__"}).attr({name:"__deleted__"});m.append(e)}c.next("tr").remove().end().remove()}});a("[name=create-option-button]").each(function(){a(this).click(function(){var c=a("#new_item_field_ul_id"),e=a("#new_item_dialog");c.val(a(this).parents("fieldset").children("ol").attr("id"));e.dialog("open").find("input:first").focus()}).hover(function(){a(this).addClass("ui-state-hover")},function(){a(this).removeClass("ui-state-hover")}).mousedown(function(){a(this).addClass("ui-state-active")}).mouseup(function(){a(this).removeClass("ui-state-active")})});
l.find(".AddQuestion").click(function(){a("#new_question_button_id").val(a(this).attr("id"));var c=a("#question_options_div");a(this).attr("id")==="choice"?c.show():c.hide();a("#new_question_dialog").dialog("open").find("input:first").focus()})}).trigger("init").bind("option_init",function(){d.find("a.delete_item").click(function(){var c=this.id.replace("del_","");a("#delete_item_field").val(c);a("#delete_item_dialog").dialog("open")}).end()}).trigger("option_init");f=a("select#id_taking_access");
var h=function(c){b.find("tr.role-specific").remove();switch(c){case "mentor evaluation":b.prepend('<tr class="role-specific"><th><label>Choose Project:</label></th><td> <select disabled=TRUE id="id_survey__NA__selection__project" name="survey__1__selection__see"><option>Survey Taker\'s ProjectsFor This Program</option></select> </td></tr>');b.append('<tr class="role-specific"><th><label>Assign Grade:</label></th><td><select disabled=TRUE id="id_survey__NA__selection__grade"name="survey__1__selection__see"><option>Pass/Fail</option></select></td></tr>');
break;case "student evaluation":b.prepend('<tr class="role-specific"><th><label>Choose Project:</label></th><td> <select disabled=TRUE id="id_survey__NA__selection__project" name="survey__1__selection__see"><option>Survey Taker\'s ProjectsFor This Program</option></select> </td></tr>');break}};f.change(function(){var c=a(this).val();h(c)});h(f.val());a("form").bind("submit",function(){b.find("tr.role-specific").remove();d.find(".long_answer,input").each(function(){a(this).attr("val",a(this).val())});
a(this).find("#id_survey_html").attr("value",d.html());d.find("input").each(function(){a(this).val()==="Write a Custom Prompt..."&&a(this).val("")});d.find(".long_answer, .tooltip_entry").each(function(){a(this).val()==="Write a Custom Prompt For This Question..."&&a(this).val("")});a("input#id_s_html").val(d.find("div#survey_options").remove().end().html());b.find(".sortable").each(function(){a("#order_for_"+this.id).val(a(this).sortable("serialize"))})})})})(jQuery);
(function(a){jQuery.fn.extend({getPosition:function(){var j=a(this).parents("fieldset:first");return j.parents("table:first").find("fieldset").index(j)+"__"}})})(jQuery);(function(a){a(function(){a(".sortable").each(function(j,d){a(d).sortable().disableSelection().end()})})})(jQuery);(function(a){a(function(){function j(d){var i=a(this).parent().attr("id").replace("-li-","_");i+="__field";a("#"+i).val(d.current)}a(".editable_option").editable({editBy:"dblclick",submit:"change",cancel:"cancel",onSubmit:j})})})(jQuery);
(function(a){a(function(){var j=["<a class='delete_item' id='del_","' ><img src='/soc/content/"+melange.config.app_version+"/images/minus.gif'/></a> "];a("#delete_item_dialog").dialog({autoOpen:false,bgiframe:true,resizable:false,height:300,modal:true,overlay:{backgroundColor:"#000",opacity:0.5},buttons:{"Delete this item":function(){a("#"+a("#delete_item_field").val()).remove();a("#delete_item_field").val("");a(this).dialog("close")},Cancel:function(){a("#delete_item_field").val("");a(this).dialog("close")}}});
a("#new_item_dialog").dialog({bgiframe:true,autoOpen:false,height:300,width:300,modal:true,buttons:{"Add option":function(){var d=a("#new_item_field_ul_id").val(),i=a("#"+d),k=a("#new_item_name").val(),g=i.find("li").length,f="id_"+d+"_"+g;d=a(['<li id="id-li-',d,"_",g,'" class="ui-state-defaolt sortable_li"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span><span id="',f,'" class="editable_option" name="',f,'__field">',k,'</span><input type="hidden" id="',f,'__field" name="',f,'__field" value="',
k.replace(/\"/g,"&quot;"),'" ></li>'].join(""));i.append(d.prepend(j.join(d.attr("id"))));i.sortable().disableSelection();a("#new_item_name").val("");a("#new_item_field_ol_id").val("");a(this).dialog("close")},Cancel:function(){a("#new_item_name").val("");a("#new_item_field_ul_id").val("");a(this).dialog("close")}}})})})(jQuery);
(function(a){a(function(){var j=["<a class='delete'><img ","src='/soc/content/"+melange.config.app_version+"/images/minus.gif'/></a>"].join(""),d=["<a class='delete_item' id='del_","' ><img src='/soc/content/"+melange.config.app_version+"/images/minus.gif'/></a> "],i=a("div#survey_widget").find("tbody:first");a("#new_question_dialog").dialog({bgiframe:true,autoOpen:false,height:400,width:300,modal:true,buttons:{"Add question":function(){var k=a("#new_question_button_id").val(),g=a("div#survey_widget").find("tbody:first");
a("#new_question_button_id").val("");var f=a(["<tr><th><label>",j,"</label></th><td>  </td></tr>"].join("")),b=a("#new_question_name").val(),l=a("#new_question_content").val(),h=a("#new_question_options").val();if(b!==""){a("#new_question_name").val("");a("#new_question_content").val("");a("#new_question_options").val("");var c=false,e=k+"__",m=g.find("fieldset").length,n=m+1+"__";switch(k){case "short_answer":c=['<fieldset>\n<label for="required_for_',b,'">Required</label><select id="required_for_',
b,'" name="required_for_',b,'"><option value="True" selected="selected">True</option><option value="False">False</option></select><label for="comment_for_',b,'">Allow Comments</label><select id="comment_for_',b,'" name="comment_for_',b,'"><option value="True" selected="selected">True</option><option value="False">False</option></select><input type=\'text\' class=\'short_answer\'></fieldset>'].join("");break;case "long_answer":g.find("fieldset");c=['<fieldset>\n<label for="required_for_',b,'">Required</label><select id="required_for_',
b,'" name="required_for_',b,'"><option value="True" selected="selected">True</option><option value="False">False</option></select><label for="comment_for_',b,'">Allow Comments</label><select id="comment_for_',b,'" name="comment_for_',b,"\"><option value=\"True\" selected=\"selected\">True</option><option value=\"False\">False</option></select><textarea wrap='hard' cols='40' rows='10' class='long_answer'/></fieldset>"].join("");break;case "selection":c="<select><option></option><option>Add A New Option...</option></select>";
break;case "pick_multi":c="<fieldset class='fieldset'><input type='button'value='Add A New Option...' /></fieldset>";break;case "choice":c="<fieldset class='fieldset'><input type='button'value='Add A New Option...' /></fieldset>";break}if(c){var o=['\n  <input type="hidden" name="NEW_',b,'" id="NEW_',b,'" value="',l.replace(/\"/g,"&quot;"),'"/>'].join("");m=g.find("fieldset").length;n=m+1+"__";e="survey__"+n+e+b;if(k==="choice"){c=a(['<fieldset>\n<label for="required_for_',b,'">Required</label><select id="required_for_',
b,'" name="required_for_',b,'"><option value="True" selected="selected">True</option><option value="False">False</option></select><label for="comment_for_',b,'">Allow Comments</label><select id="comment_for_',b,'" name="comment_for_',b,'"><option value="True" selected="selected">True</option><option value="False">False</option></select><label for="render_for_',b,'">Render as</label>\n  <select id="render_for_',b,'" name="render_for_',b,'">\n    <optionselected="selected" value="select">select</option>\n    <option value="checkboxes">checkboxes</option>\n    <option value="radio_buttons">radio_buttons</option>\n  </select>\n  <input type="hidden" id="order_for_',
b,'\n  " name="order_for_',b,'" value=""/>\n  <input type="hidden" id="index_for_',b,'\n  " name="index_for_',b,'" value="',m+1,'"/>\n  <ol id="',b,'" class="sortable"></ol>',o,'\n  <button name="create-option-button"id="create-option-button__',b,'" class="ui-button ui-state-default ui-corner-all" value="',b,'" onClick="return false;">Create new option</button>\n</fieldset>'].join(""));a(c).attr({id:"id_"+e,name:e});f.find("label").attr("for","NEW_"+b).append(l).end().find("td").append(c);g.append(f).end();
if(h){k=h.split("\n");g=a("#"+b);f=k.length;h=c=h="";for(l=0;l<f;l+=1){c="id_"+b+"_"+l;h=k[l];h=a(['<li id="id-li-',b,"_",l,'" class="ui-state-defaolt sortable_li"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span>','<span id="'+c+'" class="editable_option" name="',c,'__field">',h,'</span><input type="hidden" id="',c,'__field" name="',c,'__field" value="',h.replace(/\"/g,"&quot;"),'" ></li>'].join(""));g.append(h.prepend(d.join(h.attr("id"))));g.sortable().disableSelection()}i.trigger("option_init")}}else{c=
a(c);a(c).find(".long_answer, .short_answer").attr({id:"id_"+e,name:e});f.find("label").attr("for","id_"+e).append(l).end().find("td").append(c).append(a(o));g.append(f)}i.trigger("init")}}a("#new_question_name").val("");a("#new_question_content").val("");a("#new_question_options").val("");a(this).dialog("close")},Cancel:function(){a("#new_question_name").val("");a("#new_question_button_id").val("");a("#new_question_content").val("");a("#new_question_options").val("");a(this).dialog("close")}}})})})(jQuery);
